Update Linux

diff --git a/Linux b/Linux
--- a/Linux
+++ b/Linux
@@ -194,8 +194,19 @@ egrep               - extended grep -- is the same as grep -E. This uses a somew
                       e.g.>> $ egrep 'matches|Matches' file.txt
 enable              - This either enables or disables a shell builtin command. As an example, enable -n kill disables the shell builtin kill, so that when Bash subsequently encounters kill, it invokes the external command /bin/kill.  
 enscript            - Utility for converting plain text file to PostScript  
-exec                -   This shell builtin replaces the current process with a specified command. Normally, when the shell encounters a command, it forks off a child process to actually execute the command. Using the exec builtin, the shell does not fork, and the command exec'ed replaces the shell. When used in a script, therefore, it forces an exit from the script when the exec'ed command terminates.
+                    >> enscript oldfile.txt -p newfile.ps 
+                    # This command will convert text file into ps file.
+                    
+exec                - This shell builtin replaces the current process with a specified command. Normally, when the shell encounters a command, it forks off a child process to actually execute the command. Using the exec builtin, the shell does not fork, and the command exec'ed replaces the shell. When used in a script, therefore, it forces an exit from the script when the exec'ed command terminates.
+                    >> exec echo "we are exiting $0 at line number $LINENO"   #here $0 is script name( first positional parameter) and 
+                                                                              #$LINENO is the editor line number variable.
 exit                - Unconditionally terminates a script. The exit command may optionally take an integer argument, which is returned to the shell as the exit status of the script. example exit 0 or exit $?  
+                    echo "test print"
+                    exit 20    # here even though echo is successful , instead of printing exit status as 0 , we are printing 20(some
+                               # other number. but it is possible to print 0 (true) or false (1) status as shown below
+                    echo "new test"
+                    false      # this will print 1 if we do echo $?  
+                    
 export              - The export [4] command makes available variables to all child processes of the running script or shell. One important use of the export command is in startup files, to initialize and make accessible environmental variables to subsequent user processes.  
 expr                - All-purpose expression evaluator: Concatenates and evaluates the arguments according to the operation given (arguments must be separated by spaces). Operations may be arithmetic, comparison, string, or logical.  
                       e.g expr 3 + 5              # 8
