Update Linux- Basics-tests

diff --git a/Linux- Basics-tests b/Linux- Basics-tests
--- a/Linux- Basics-tests
+++ b/Linux- Basics-tests
@@ -118,7 +118,64 @@ ls -l 2>&1 >&3 3>&- | grep bad 3>&-    # Close fd 3 for 'grep' (but not 'ls').
 exec 3>&-                              # Now close it for the remainder of the script.
 
 ----------------------------Functions -----------------------------------
+function_name () { 
+command... 
+} 
 
+fun () { echo "This is a function"; echo; }      # A function may be "compacted" into a single line.
+#                                 ^     ^
+
+- function cannot be empty.
+- _() or :() are acceptable function name
+- ls -l | foo() { echo "foo"; }  # Permissible, but useless.
+- It is possible to do nested functions 
+---------program 1 ---
+f1 ()
+{
+  f2 () # nested
+  {
+    echo "Function \"f2\", inside \"f1\"."
+  }
+}  
+
+f2  #  Gives an error message.
+    #  Even a preceding "declare -f f2" wouldn't help.
+echo    
+f1  #  Does nothing, since calling "f1" does not automatically call "f2".
+f2  #  Now, it's all right to call "f2",
+    #+ since its definition has been made visible by calling "f1".
+
+----------Program2---
+if [ "$USER" = bozo ]
+then
+  bozo_greet ()   # Function definition embedded in an if/then construct.
+  {
+    echo "Hello, Bozo."
+  }
+fi  
+bozo_greet        # Works only for Bozo, and other users get an error.
+
+----------Program3---
+filename=file1
+[ -f "$filename" ] &&
+foo () { rm -f "$filename"; echo "File "$filename" deleted."; } ||
+foo () { echo "File "$filename" not found."; touch bar; }
+
+foo        # File file1 not found
+
+----------Program3 ---
+func ()
+{
+  echo "First version of func ()."
+}
+func ()
+{
+  echo "Second version of func ()."
+}
+func   # Second version of func ().
+exit $?
+
+-------------------------------------List Constructs-------------------------------
 
 
 
